/*
	prob 2.c - Solution to Problem 2 of Project Euler
	Copyright (C) 2012, Shubham Verma

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

*/


/*

Problem -

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.

Ans - 4613732

*/

int main()
{
    int i, a, b, c, sum=0;
    
    a=0;
    b=1;
   
    for(i=1; c<4000000; i++)
    {
        c = a+b;     

        //printf("\nc - %d", c);
        
        if(c%2==0)
        {
            sum = sum+c;
            //printf(" even  sum - %d", sum);
        }
        //else
            //printf(" odd"); 
         
        a=b;
        b=c;     
    }

    printf("\n%d", sum);
    
    getch();
    
    return 0;
}
