/*

The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 

The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over 
five hundred divisors?

Ans - 76576500

*/

typedef unsigned long long ULNG;

int numOfDivisors(ULNG x)
{
    int count;
    ULNG i;
    
    count = 2;
    
    if(x == 1)
       return 1;
    
    for(i=2; i<(x/2+1); i++)
    {
         if(x%i==0)
           count++;    
         
    }
    
    return count;    
}

int main()
{
    ULNG sum, ans, i;
    int nod;
      
    sum = 0;
    
    for(i=1 ; ; i++)
    {
         sum = sum + i;
         nod = numOfDivisors(sum);   
         printf("\nsum - %llu  numOfDivisors - %d  i - %llu", sum, nod, i);
         if(nod > 500)
         {
               ans = sum;
               break; 
         } 
    }

    printf("\nAns - %llu", sum); 
       
    getch();
    
    return 0;
}
